name = "xim"
uuid = "787343da-71de-44cb-a2e4-ef03eb6af488"
authors = ["Nelson Lopes", "IST"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
